---
- name: webserver playbook
  become: true
  hosts: all
  tasks:
    - package: 
        name: httpd
        state: present
    - service: 
        name: httpd
        state: started
    - copy:
        src: web/index.html
        dest: /var/www/html
    - copy:
        src: web/west.jpg
        dest: /var/www/html
